fix(confirm): now the "confirm" method in index.d.ts returns the correct type (boolean)
TopCli/prompts pull request #18
Opened 2023-06-24 20:02 UTC by SofianD

2023-06-24 20:43 UTC, PierreDemailly requested changes
@SofianD Can you please update README ?

2023-06-24 20:56 UTC, PierreDemailly approved these changes

2023-06-25 10:57 UTC, fraxken approved these changes

2023-06-25 12:35 UTC, merged

2023-06-25 12:36 UTC, PierreDemailly commented
@all-contributors please add @SofianD for code, doc