chore: updated prompts to latest demo.js
TopCli/prompts pull request #34
Opened 2023-07-30 04:46 UTC by JUSTIVE

it resolves #33 
It would be good to have a script for auto-gen README.md to make sure it's up-to-date, but I'll leave it as future work

2023-07-31 18:56 UTC, PierreDemailly requested changes
Thanks for contributing :) Just a small thing to update

2023-07-31 18:56 UTC, PierreDemailly commented on README.md
> +import { question, confirm, select } from "./index.js";
This code snippet represents a basic usage example using the package as third party library, not locally 
```suggestion
import { question, confirm, select } from "@topcli/prompts";
```

2023-08-01 03:12 UTC, JUSTIVE commented
accepted your request! thanks!

2023-08-01 14:40 UTC, PierreDemailly approved these changes

2023-08-01 14:43 UTC, merged